# Generated by Django 3.1.7 on 2021-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipertension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipertension',
            name='resultado',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
