# Generated by Django 3.1.7 on 2021-05-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hipertension', '0002_hipertension_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hipertension',
            old_name='presion_d',
            new_name='peso',
        ),
        migrations.RemoveField(
            model_name='hipertension',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='hipertension',
            name='colesterol_t',
        ),
        migrations.RemoveField(
            model_name='hipertension',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='hipertension',
            name='nombre',
        ),
    ]
