# Generated by Django 3.1.3 on 2021-02-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucosa_plasmatica', models.IntegerField(verbose_name='Glucosa plasmatica')),
                ('presion_arterial', models.IntegerField(verbose_name='Presion Arterial')),
                ('espesor_piel', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Espesor de la piel')),
                ('insulina', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='insulina')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Indice masa muscular')),
                ('pedigri_diabetes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pedigri diabetes')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
